import Navigation from "@/components/Navigation";
import { Inter } from "@next/font/google";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import "./globals.css";
import NextAuthProvider from "./provider/NextAuthProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Define a custom CSS variable
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nextAuthSession = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased font-sans`}>
        <NextAuthProvider session={nextAuthSession}>
          <Navigation />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
