export const sortOptions = [
    'province',
    'cuisine'
];

export const provinceOptions = [
    'Bangkok',
    'Chiang Mai',
    'Phuket',
    'Chonburi',
    'Nakhon Ratchasima',
    'Songkhla',
    'Khon Kaen',
    'Ayutthaya',
    'Nakhon Si Thammarat',
    'Ubon Ratchathani',
    'Nonthaburi',
    'Pathum Thani',
    'Samut Prakan',
    'Surat Thani',
    'Chiang Rai',
    'Udon Thani',
    'Nakhon Pathom',
    'Prachuap Khiri Khan',
    'Rayong',
    'Lampang',
    'Loei',
    'Ratchaburi',
    'Pattani',
    'Trang',
    'Sukhothai',
    'Suphan Buri',
    'Chaiyaphum',
    'Sakon Nakhon',
    'Phetchabun',
    'Sa Kaeo',
    'Mukdahan',
    'Amnat Charoen',
    'Chai Nat',
    'Nong Khai',
    'Kamphaeng Phet',
    'Tak',
    'Phitsanulok',
    'Phichit',
    'Saraburi',
    'Phrae',
    'Nong Bua Lamphu',
    'Buri Ram',
    'Singburi',
    'Kanchanaburi',
    'Nakhon Nayok',
    'Chumphon',
    'Mae Hong Son',
    'Phetchaburi',
    'Narathiwat',
    'Yala',
    'Pong Nam Ron',
    'Ranong'
];
  
  
export const cuisineOptions = [
    'Italian',
    'Chinese',
    'Indian',
    'Mexican',
    'Japanese',
    'French',
    'Thai',
    'Greek',
    'Spanish',
    'Lebanese',
    'Turkish',
    'Vietnamese',
    'Korean',
    'Middle Eastern',
    'American',
    'Brazilian',
    'Caribbean',
    'Ethiopian',
    'Moroccan',
    'Russian',
    'African',
    'Australian'
];
